-- =============================================================================
-- Nạp QLPN.GTH_KY_GIAM_THOI_HANS từ QLPN_OLD.PN_OPEN_KY_GIAM_THOI_HAN
-- Quy ước migrate: .cursor/rules/sql-migration-qlpn-conventions.mdc
--   - Không INSERT: ID, CREATOR_USER_ID, LAST_MODIFICATION_TIME,
--     LAST_MODIFIER_USER_ID, DELETER_USER_ID, DELETION_TIME
--   - MA_DP* → MAPPING_PROVINCE + DM_TINH_THANH_PHO (ID tỉnh), không DM_DON_VI_HANH_CHINH
-- Chưa map sang bảng đích: NGAY_XET_MOI, DIEU_KIEN_GIAM, ACTION, CO_HIEU_LUC (KGTH_TRANG_THAI mặc định 1)
-- =============================================================================
DELETE FROM QLPN.GTH_KY_GIAM_THOI_HANS;
INSERT /*+ APPEND */ INTO QLPN.GTH_KY_GIAM_THOI_HANS (
    KGTH_NAM,
    KGTH_TEN_KY,
    KGTH_NGAY_XET_GIAM,
    KGTH_NGAY_DE_NGHI,
    KGTH_NGAY_HOP_XET,
    KGTH_NGAY_PHIEU_GIAM,
    KGTH_CO_TINH_NGAY_THANG,
    KGTH_TRANG_THAI,
    KGTH_MA_XAC_THUC,
    KGTH_DA_KHOA_LAN_DAU,
    KGTH_TOA_QUYET_DINH_GIAM_ID,
    KGTH_DIA_PHUONG_TOA_ID,
    CREATION_TIME,
    IS_DELETED
)
WITH gth_ky_src AS (
    SELECT
        CAST(TO_CHAR(k.NGAY_XET_GIAM, 'YYYY') AS NVARCHAR2(8)) AS KGTH_NAM,
        N'Kỳ giảm thời hạn ' || CAST(TO_CHAR(k.NGAY_XET_GIAM, 'YYYY') AS NVARCHAR2(8)) AS KGTH_TEN_KY,
        CAST(k.NGAY_XET_GIAM AS TIMESTAMP(7)) AS KGTH_NGAY_XET_GIAM,
        CAST(k.NGAY_DE_NGHI AS TIMESTAMP(7)) AS KGTH_NGAY_DE_NGHI,
        CAST(k.NGAY_HOP_XET AS TIMESTAMP(7)) AS KGTH_NGAY_HOP_XET,
        CAST(k.NGAY_VAN_BAN AS TIMESTAMP(7)) AS KGTH_NGAY_PHIEU_GIAM,
        k.CO_TINH_NGAY AS KGTH_CO_TINH_NGAY_THANG,
        0 AS KGTH_TRANG_THAI,
        NULLIF(TRIM(CAST(k.GHI_CHU AS NVARCHAR2(2000))), N'') AS KGTH_MA_XAC_THUC,
        CAST(NULL AS NUMBER) AS KGTH_DA_KHOA_LAN_DAU,
        cq.ID AS KGTH_TOA_QUYET_DINH_GIAM_ID,
        dttp.ID AS KGTH_DIA_PHUONG_TOA_ID,
        SYSTIMESTAMP AS CREATION_TIME,
        0 AS IS_DELETED
    FROM QLPN_OLD.PN_OPEN_KY_GIAM_THOI_HAN k
    LEFT JOIN QLPN.DM_CO_QUANS cq
        ON TRIM(CAST(cq.CQ_MA AS VARCHAR2(4000))) = TRIM(CAST(k.MA_CQ_TOA_QD_GIAM AS VARCHAR2(4000)))
       AND NVL(cq.IS_DELETED, 0) = 0
    LEFT JOIN QLPN.MAPPING_PROVINCE mp_dp
        ON TRIM(TO_CHAR(mp_dp.MA_TINH_OLD)) = TRIM(TO_CHAR(k.MA_DP_TOA_QD_GIAM))
    LEFT JOIN QLPN.DM_TINH_THANH_PHO dttp
        ON TRIM(CAST(mp_dp.MA_TINH_NEW AS VARCHAR2(4000))) = TRIM(CAST(dttp.TTP_MA AS VARCHAR2(4000)))
       AND NVL(dttp.IS_DELETED, 0) = 0
)
SELECT
    s.KGTH_NAM,
    s.KGTH_TEN_KY,
    s.KGTH_NGAY_XET_GIAM,
    s.KGTH_NGAY_DE_NGHI,
    s.KGTH_NGAY_HOP_XET,
    s.KGTH_NGAY_PHIEU_GIAM,
    s.KGTH_CO_TINH_NGAY_THANG,
    s.KGTH_TRANG_THAI,
    s.KGTH_MA_XAC_THUC,
    s.KGTH_DA_KHOA_LAN_DAU,
    s.KGTH_TOA_QUYET_DINH_GIAM_ID,
    s.KGTH_DIA_PHUONG_TOA_ID,
    s.CREATION_TIME,
    s.IS_DELETED
FROM gth_ky_src s;
COMMIT;