DELETE FROM "QLPN"."MIEN_HINH_PHATS";
INSERT INTO "QLPN"."MIEN_HINH_PHATS" (
    "MHP_SO_DE_NGHI", "MHP_NGAY_DE_NGHI", "MHP_SO_QUYET_DINH", "MHP_NGAY_QUYET_DINH",
    "MHP_TOA_QUYET_DINH", "MHP_DIA_PHUONG_QD", "MHP_TRUONG_HOP_MIEN", "MHP_TOI_DE_NGHI_MIEN",
    "MHP_TOI_DANH_MIEN", "MHP_NGAY_TU_DO", "MHP_NHAN_XET", "PN_LAI_LICH_ID",
    "MHP_MATM_YEAR", "MHP_MATM_MONTH", "MHP_MATM_DAY",
    "MHP_THM_YEAR", "MHP_THM_MONTH", "MHP_THM_DAY",
    "CREATION_TIME", "IS_DELETED"
)
SELECT
    "CV_DN_MIEN_SO" MHP_SO_DE_NGHI
    ,CV_DN_MIEN_NGAY MHP_NGAY_DE_NGHI
    ,"QD_MIEN_SO" MHP_SO_QUYET_DINH
    ,QD_MIEN_NGAY MHP_NGAY_QUYET_DINH
    ,DCQ.ID MHP_TOA_QUYET_DINH
    ,DDVHC.ID MHP_DIA_PHUONG_QD
    ,DTHMHP.ID MHP_TRUONG_HOP_MIEN
    ,DTDS.ID MHP_TOI_DE_NGHI_MIEN
    ,DTD.ID MHP_TOI_DANH_MIEN
    ,NGAY_TRA_TU_DO "MHP_NGAY_TU_DO"
    ,DANH_GIA_CAI_TAO "MHP_NHAN_XET"
    ,PLLS.ID "PN_LAI_LICH_ID"
    ,NULL "MHP_MATM_YEAR"
    ,NULL "MHP_MATM_MONTH"
    ,NULL "MHP_MATM_DAY"
    ,NULL "MHP_THM_YEAR"
    ,NULL "MHP_THM_MONTH"
    ,NULL "MHP_THM_DAY"
    ,SYSDATE AS CREATION_TIME
    ,0 AS IS_DELETED
FROM "QLPN_OLD"."PN_MIEN_HINH_PHAT" PMHP
INNER JOIN "QLPN_OLD".PN_LAI_LICH PLL
ON PMHP.PN_ID = PLL.PN_ID
INNER JOIN "QLPN".PN_LAI_LICHS PLLS
ON PLL.SO_HSLD = PLLS.LL_SO_HO_SO_LAN_DAU
LEFT JOIN "QLPN".DM_DON_VI_HANH_CHINH DDVHC ON DDVHC.DVHC_MA_DVHC = PMHP.MA_DP_TOA_QD_MIEN
LEFT JOIN "QLPN".DM_CO_QUANS DCQ ON DCQ.CQ_MA = PMHP.MA_CQ_TOA_QD_MIEN
LEFT JOIN "QLPN"."DM_TRUONG_HOP_MIEN_HINH_PHATS" DTHMHP ON DTHMHP.MHP_MA = PMHP.MA_TRUONG_HOP_MIEN
LEFT JOIN "QLPN"."DM_TOI_DANHS" DTD ON DTD.TD_MA = PMHP.MA_TOI_DANH_MIEN
LEFT JOIN "QLPN"."DM_TOI_DANHS" DTDS ON DTDS.TD_MA = PMHP.MA_TOI_DANH_TRUOC_MIEN;