DELETE FROM QLPN.HUY_ANS;
INSERT INTO QLPN.HUY_ANS
(
TOA_QUYET_DINH_ID,
SO_QUYET_DINH,
PHAM_NHAN_ID,
NGAY_TRO_LAI,
NGAY_TRA_TU_DO,
NGAY_QUYET_DINH,
LY_DO_HUY ,
GHI_CHU,
DIA_PHUONG_ID,
CREATION_TIME,
IS_DELETED
)
SELECT
MA_CQ_TOA_HUY,
SO_QD_HUY,
LLN.ID PN_ID,
NGAY_LAI,
NGAY_TRA_TUDO,
NGAY_QD_HUY,
LY_DO_HUY,
GHI_CHU,
MA_DP_TOA_HUY,
CAST(SYSTIMESTAMP AS TIMESTAMP(7)) AS CREATION_TIME,
0 AS IS_DELETED
FROM QLPN_OLD.PN_HUY_AN PHA
INNER JOIN QLPN_OLD.PN_LAI_LICH LL ON PHA.PN_ID = LL.PN_ID
INNER JOIN QLPN.PN_LAI_LICHS LLN ON LL.SO_HSLD = LLN.LL_SO_HO_SO_LAN_DAU
LEFT JOIN QLPN.DM_CO_QUANS DCQ ON DCQ.CQ_MA = PHA.MA_CQ_TOA_HUY
LEFT JOIN QLPN.DM_DON_VI_HANH_CHINH DVHC ON DVHC.DVHC_MA_DVHC = PHA.MA_DP_TOA_HUY;