DELETE FROM QLPN.PN_LAI_LICHS;
INSERT INTO QLPN.PN_LAI_LICHS (LL_SO_HO_SO_LAN_DAU, LL_SO_HO_PHU, LL_CCCD, LL_HO_CHIEU, LL_HO_TEN, LL_TEN_KHAC, LL_DIA_CHI_THUONG_TRU, LL_NOI_OTRUOC_KHI_BAT, LL_NOI_THA_VE_CU_TRU, LL_NOI_OKHAC, LL_NGUYEN_QUAN, LL_CHI_TIET_HV, LL_TOM_TAT_HV, LL_CHI_MUC_TIM_KIEM, LL_TRINH_DO_CHUYEN_MON, LL_NGHE_CU_THE, LL_CHI_TIET_BENH_VAO, LL_CHI_TIET_BENH_HIEN_TAI, LL_GHI_CHU_RIENG, LL_PHAN_DOI_ID, LL_TINH_TRANG_ID, LL_TRAI_GIAM_ID, LL_TINH_TRANG_HOC_TAP_ID, LL_NGAY_SINH, LL_GHI_CHU_CHUNG_HPBS, LL_BIET_DOC_VIET_ID, LL_BENH_TAT_VAO_ID, LL_DM_GIOI_TINH_ID, LL_DM_NGHE_NGHIEP_ID, LL_DM_HOC_VAN_ID, LL_DM_QUOC_TICH_ID, LL_DM_TON_GIAO_ID, LL_DM_DAN_TOC_ID, LL_SUC_KHOE_KHI_VAO_ID, LL_SO_TIEN_SU, LL_GHI_CHU_TIEN_SU, LL_SO_TIEN_AN, LL_TAI_PHAM, LL_NHAN_THAN, CREATION_TIME, IS_DELETED,
                               LL_ANH, LL_BENH_HIEN_TAI, LL_GHI_CHU_CHI_TIET, LL_TRINH_DO_HOC_VAN_ID,
                               LL_DIA_CHI_THUONG_TRU_PROVICE, LL_DIA_CHI_THUONG_TRU_WARD,
                               LL_NOI_OTRUOC_KHI_BAT_PROVICE, LL_NOI_OTRUOC_KHI_BAT_WARD,
                               LL_NOI_OKHAC_PROVICE, LL_NOI_OKHAC_WARD,
                               LL_NOI_THA_VE_CU_TRU_PROVICE, LL_NOI_THA_VE_CU_TRU_WARD,
                               LL_PN_GIAO_NHAN_PHAN_NHAN_ID,
                               CREATOR_USER_ID, LAST_MODIFICATION_TIME, LAST_MODIFIER_USER_ID, DELETER_USER_ID, DELETION_TIME,
                               LL_PHAN_TRAI_ID, LL_SO_GCN, PN_MA_TINH_TRANG_TRICH_XUAT,
                               LL_DIA_CHI_THA_VE_CU_TRU_CU, LL_DIA_CHI_THUONG_TRU_CU, LL_DIA_CHI_TRUOC_KHI_BAT_CU)
SELECT SO_HSLD AS LL_SO_HO_SO_LAN_DAU,
       SO_HSPHU AS LL_SO_HO_PHU,
       CASE
           WHEN NOT REGEXP_LIKE(COALESCE(SO_CCCD, SO_CMND), '[[:alpha:]]') THEN COALESCE(SO_CCCD, SO_CMND)
           ELSE NULL
       END AS LL_CCCD,
       CASE
           WHEN REGEXP_LIKE(COALESCE(SO_CCCD, SO_CMND), '[[:alpha:]]') THEN COALESCE(SO_CCCD, SO_CMND)
           ELSE NULL
       END AS LL_HO_CHIEU,
       HO_TEN AS LL_HO_TEN,
       TEN_KHAC AS LL_TEN_KHAC,
       pll.DC_TT_THON_PHO || ', ' || pll.DC_TT_PHUONG_XA AS LL_DIA_CHI_THUONG_TRU,
       pll.DC_VAO_THON_PHO || ', ' || pll.DC_VAO_PHUONG_XA AS LL_NOI_OTRUOC_KHI_BAT,
       pll.DC_VE_THON_PHO || ', ' || pll.DC_VE_PHUONG_XA AS LL_NOI_THA_VE_CU_TRU,
       CHO_O_KHAC AS LL_NOI_OKHAC,
       NGUYEN_QUAN AS LL_NGUYEN_QUAN,
       CHI_TIET_HV AS LL_CHI_TIET_HV,
       TOM_TAT_HV AS LL_TOM_TAT_HV,
       CHI_MUC_TIM_KIEM AS LL_CHI_MUC_TIM_KIEM,
       TRINH_DO_CHUYEN_MON AS LL_TRINH_DO_CHUYEN_MON,
       NGHE_CU_THE AS LL_NGHE_CU_THE,
       BENH_TAT_VAO AS LL_CHI_TIET_BENH_VAO,
       BENH_TAT_HT AS LL_CHI_TIET_BENH_HIEN_TAI,
       GHI_CHU_RIENG AS LL_GHI_CHU_RIENG,
       dbt.ID AS LL_PHAN_DOI_ID,
       ttpn.ID AS LL_TINH_TRANG_ID,
       trg.ID AS LL_TRAI_GIAM_ID,
       ttht.ID AS LL_TINH_TRANG_HOC_TAP_ID,
       NGAY_SINH_PN AS LL_NGAY_SINH,
       GHI_CHU_HPBS AS LL_GHI_CHU_CHUNG_HPBS,
       bdv.ID AS LL_BIET_DOC_VIET_ID,
       bt.ID AS LL_BENH_TAT_VAO_ID,
       gt.ID AS LL_DM_GIOI_TINH_ID,
       nn.ID AS LL_DM_NGHE_NGHIEP_ID,
       hv.ID AS LL_DM_HOC_VAN_ID,
       qt.ID AS LL_DM_QUOC_TICH_ID,
       tg.ID AS LL_DM_TON_GIAO_ID,
       dt.ID AS LL_DM_DAN_TOC_ID,
       sk.ID AS LL_SUC_KHOE_KHI_VAO_ID,
       SO_TIEN_SU AS LL_SO_TIEN_SU,
       GHI_CHU_TIEN_SU AS LL_GHI_CHU_TIEN_SU,
       SO_TIEN_AN AS LL_SO_TIEN_AN,
       tp.ID AS LL_TAI_PHAM,
       NHAN_THAN AS LL_NHAN_THAN,
       SYSDATE AS CREATION_TIME,
       0 AS IS_DELETED,
       NULL AS LL_ANH,
       NULL AS LL_BENH_HIEN_TAI,
       NULL AS LL_GHI_CHU_CHI_TIET,
       NULL AS LL_TRINH_DO_HOC_VAN_ID,
       dttp_tt.ID AS LL_DIA_CHI_THUONG_TRU_PROVICE,
       dxp_tt.ID AS LL_DIA_CHI_THUONG_TRU_WARD,
       dttp_vao.ID AS LL_NOI_OTRUOC_KHI_BAT_PROVICE,
       dxp_vao.ID AS LL_NOI_OTRUOC_KHI_BAT_WARD,
       NULL AS LL_NOI_OKHAC_PROVICE,
       NULL AS LL_NOI_OKHAC_WARD,
       dttp_ve.ID AS LL_NOI_THA_VE_CU_TRU_PROVICE,
       dxp_ve.ID AS LL_NOI_THA_VE_CU_TRU_WARD,
       NULL AS LL_PN_GIAO_NHAN_PHAN_NHAN_ID,
       NULL AS CREATOR_USER_ID,
       NULL AS LAST_MODIFICATION_TIME,
       NULL AS LAST_MODIFIER_USER_ID,
       NULL AS DELETER_USER_ID,
       NULL AS DELETION_TIME,
       dbt.PD_DM_PHAN_TRAI_ID AS LL_PHAN_TRAI_ID,
       NULL AS LL_SO_GCN,
       NULL AS PN_MA_TINH_TRANG_TRICH_XUAT,
       pll.DC_VE_THON_PHO || ', ' || pll.DC_VE_PHUONG_XA || ', ' || mve.ND  AS LL_DIA_CHI_THA_VE_CU_TRU_CU,
       pll.DC_TT_THON_PHO || ', ' || pll.DC_TT_PHUONG_XA || ', ' || mtt.ND AS LL_DIA_CHI_THUONG_TRU_CU,
       pll.DC_VAO_THON_PHO || ', ' || pll.DC_VAO_PHUONG_XA || ', ' || mvao.ND AS LL_DIA_CHI_TRUOC_KHI_BAT_CU
FROM QLPN_OLD.PN_LAI_LICH pll
LEFT JOIN QLPN.DM_PHAN_DOIS dbt ON pll.MA_PHAN_DOI = dbt.PD_MA
AND dbt.IS_DELETED = 0
LEFT JOIN QLPN.DM_TINH_TRANG_PHAM_NHANS ttpn ON pll.MA_TINH_TRANG = ttpn.TTPN_MA
AND ttpn.IS_DELETED = 0
LEFT JOIN QLPN.DM_TRAI_GIAMS trg ON pll.MA_TRAI_GIAM = trg.TG_MA
AND trg.IS_DELETED = 0
LEFT JOIN QLPN.DM_TINH_TRANG_HOC_TAP_PHAM_NHAN_VI_THANH_NIENS ttht ON pll.MA_TINH_TRANG_HOC_TAP = ttht.TTHTPNVTN_MA
AND ttht.IS_DELETED = 0
LEFT JOIN QLPN.DM_TINH_TRANG_BIET_DOC_VIETS bdv ON pll.MA_TINH_TRANG_DOC_VIET = bdv.TTBDV_MA
AND bdv.IS_DELETED = 0
LEFT JOIN QLPN.DM_BENH_TATS bt ON pll.MA_BENH_TAT_VAO = bt.BT_MA
AND bt.IS_DELETED = 0
LEFT JOIN QLPN.DM_GIOI_TINHS gt ON pll.MA_GIOI_TINH = gt.GT_MA
AND gt.IS_DELETED = 0
LEFT JOIN QLPN.DM_NGHE_NGHIEPS nn ON pll.MA_NGHE_NGHIEP = nn.NN_MA
AND nn.IS_DELETED = 0
LEFT JOIN QLPN.DM_HOC_VANS hv ON pll.MA_HOC_VAN = hv.HV_MA
AND hv.IS_DELETED = 0
LEFT JOIN QLPN.DM_QUOC_TICHS qt ON pll.MA_QUOC_TICH = qt.QT_MA
AND qt.IS_DELETED = 0
LEFT JOIN QLPN.DM_TON_GIAOS tg ON pll.MA_TON_GIAO = tg.TG_MA
AND tg.IS_DELETED = 0
LEFT JOIN QLPN.DM_DAN_TOCS dt ON pll.MA_DAN_TOC = dt.DT_MA
AND dt.IS_DELETED = 0
LEFT JOIN QLPN.DM_TINH_TRANG_SUC_KHOE_PHAM_NHANS sk ON pll.MA_SUC_KHOE_VAO = sk.TTSKPN_MA
AND sk.IS_DELETED = 0
LEFT JOIN QLPN.DM_TAI_PHAMS tp ON pll.MA_TAI_PHAM = tp.TP_MA
AND tp.IS_DELETED = 0
LEFT JOIN QLPN_OLD.MA_DP mtt ON pll.MA_DP_DC_TT = mtt.MA
LEFT JOIN QLPN_OLD.MA_DP mvao ON pll.MA_DP_DC_VAO = mvao.MA
LEFT JOIN QLPN_OLD.MA_DP mve ON pll.MA_DP_DC_VE = mve.MA
LEFT JOIN QLPN.MAPPING_PROVINCE mp_tt
  ON TRIM(TO_CHAR(mp_tt.MA_TINH_OLD)) = TRIM(pll.MA_DP_DC_TT)
LEFT JOIN QLPN.DM_TINH_THANH_PHO dttp_tt
  ON TRIM(mp_tt.MA_TINH_NEW) = TRIM(dttp_tt.TTP_MA)
 AND NVL(dttp_tt.IS_DELETED, 0) = 0
LEFT JOIN QLPN.MAPPING_PROVINCE mp_vao
  ON TRIM(TO_CHAR(mp_vao.MA_TINH_OLD)) = TRIM(pll.MA_DP_DC_VAO)
LEFT JOIN QLPN.DM_TINH_THANH_PHO dttp_vao
  ON TRIM(mp_vao.MA_TINH_NEW) = TRIM(dttp_vao.TTP_MA)
 AND NVL(dttp_vao.IS_DELETED, 0) = 0
LEFT JOIN QLPN.MAPPING_PROVINCE mp_ve
  ON TRIM(TO_CHAR(mp_ve.MA_TINH_OLD)) = TRIM(pll.MA_DP_DC_VE)
LEFT JOIN QLPN.DM_TINH_THANH_PHO dttp_ve
  ON TRIM(mp_ve.MA_TINH_NEW) = TRIM(dttp_ve.TTP_MA)
 AND NVL(dttp_ve.IS_DELETED, 0) = 0
LEFT JOIN QLPN.DM_XA_PHUONG dxp_tt
  ON NVL(dxp_tt.IS_DELETED, 0) = 0
 AND TRIM(dxp_tt.XP_MA_TINH_THANH_PHO) = TRIM(mp_tt.MA_TINH_NEW)
 AND REGEXP_REPLACE(TRIM(pll.DC_TT_PHUONG_XA), '^(Xã|Phường)\s+', '', 1, 0, 'i')
     = REGEXP_REPLACE(TRIM(dxp_tt.XP_TEN), '^(Xã|Phường)\s+', '', 1, 0, 'i')
LEFT JOIN QLPN.DM_XA_PHUONG dxp_vao
  ON NVL(dxp_vao.IS_DELETED, 0) = 0
 AND TRIM(dxp_vao.XP_MA_TINH_THANH_PHO) = TRIM(mp_vao.MA_TINH_NEW)
 AND REGEXP_REPLACE(TRIM(pll.DC_VAO_PHUONG_XA), '^(Xã|Phường)\s+', '', 1, 0, 'i')
     = REGEXP_REPLACE(TRIM(dxp_vao.XP_TEN), '^(Xã|Phường)\s+', '', 1, 0, 'i')
LEFT JOIN QLPN.DM_XA_PHUONG dxp_ve
  ON NVL(dxp_ve.IS_DELETED, 0) = 0
 AND TRIM(dxp_ve.XP_MA_TINH_THANH_PHO) = TRIM(mp_ve.MA_TINH_NEW)
 AND REGEXP_REPLACE(TRIM(pll.DC_VE_PHUONG_XA), '^(Xã|Phường)\s+', '', 1, 0, 'i')
     = REGEXP_REPLACE(TRIM(dxp_ve.XP_TEN), '^(Xã|Phường)\s+', '', 1, 0, 'i');