-- =============================================================================
-- SCRIPT_CHUYEN_TRAI.sql — Nạp PHAM_NHAN_CHUYEN_TRAI từ QLPN_OLD.PN_CHUYEN_TRAI
-- Quy ước migrate: .cursor/rules/sql-migration-qlpn-conventions.mdc
--   - Không INSERT: ID, CREATOR_USER_ID, LAST_MODIFICATION_TIME,
--     LAST_MODIFIER_USER_ID, DELETER_USER_ID, DELETION_TIME
--   - MA_DP* → MAPPING_PROVINCE + DM_TINH_THANH_PHO (ID tỉnh), không DM_DON_VI_HANH_CHINH
-- Nguồn còn MA_CQ_QD_CHUYEN, MA_DP_QD_CHUYEN — chưa có cột tương ứng trên PHAM_NHAN_CHUYEN_TRAI.
-- Nếu TRUNCATE lỗi FK: đổi thành DELETE FROM QLPN.PHAM_NHAN_CHUYEN_TRAI;
-- =============================================================================
TRUNCATE TABLE QLPN.PHAM_NHAN_CHUYEN_TRAI;
INSERT /*+ APPEND */ INTO QLPN.PHAM_NHAN_CHUYEN_TRAI (
    PNCT_CONG_VAN_DE_NGHI_SO,
    PNCT_CONG_VAN_DE_NGHI_NGAY,
    PNCT_CO_QUAN_DE_NGHI_CHUYEN_ID,
    PNCT_SO_QDDIEU_CHUYEN,
    PNCT_NGAY_QDCHUYEN,
    PNCT_TRUONG_HOP_CHUYEN_ID,
    PNCT_NGAY_CHUYEN,
    PNCT_TRAI_DEN_ID,
    PNCT_NGAY_TRO_LAI,
    PNCT_SO_QDDIEU_CHUYEN_LAI,
    PNCT_NGAY_QDDIEU_CHUYEN_LAI,
    PNCT_GHI_CHU,
    PNCT_LAI_LICH_ID,
    PNCT_CO_QUAN_DE_NGHI_DIA_PHUONG_ID,
    PNCT_TRAI_DEN_DIA_PHUONG_ID,
    CREATION_TIME,
    IS_DELETED
)
WITH chuyen_trai_src AS (
    SELECT
        ct.CV_DN_CHUYEN_SO AS PNCT_CONG_VAN_DE_NGHI_SO,
        CAST(ct.CV_DN_CHUYEN_NGAY AS TIMESTAMP(7)) AS PNCT_CONG_VAN_DE_NGHI_NGAY,
        cq_dn.ID AS PNCT_CO_QUAN_DE_NGHI_CHUYEN_ID,
        ct.SO_QD_CHUYEN AS PNCT_SO_QDDIEU_CHUYEN,
        CAST(ct.NGAY_QD_CHUYEN AS TIMESTAMP(7)) AS PNCT_NGAY_QDCHUYEN,
        thct.ID AS PNCT_TRUONG_HOP_CHUYEN_ID,
        CAST(ct.NGAY_CHUYEN AS TIMESTAMP(7)) AS PNCT_NGAY_CHUYEN,
        tg_den.ID AS PNCT_TRAI_DEN_ID,
        CAST(ct.NGAY_TRO_LAI AS TIMESTAMP(7)) AS PNCT_NGAY_TRO_LAI,
        ct.QD_TRO_LAI_SO AS PNCT_SO_QDDIEU_CHUYEN_LAI,
        CAST(ct.QD_TRO_LAI_NGAY AS TIMESTAMP(7)) AS PNCT_NGAY_QDDIEU_CHUYEN_LAI,
        ct.GHI_CHU AS PNCT_GHI_CHU,
        plls.ID AS PNCT_LAI_LICH_ID,
        dttp_dn.ID AS PNCT_CO_QUAN_DE_NGHI_DIA_PHUONG_ID,
        dttp_trai.ID AS PNCT_TRAI_DEN_DIA_PHUONG_ID,
        SYSTIMESTAMP AS CREATION_TIME,
        0 AS IS_DELETED
    FROM QLPN_OLD.PN_CHUYEN_TRAI ct
    INNER JOIN QLPN_OLD.PN_LAI_LICH pll_old
        ON ct.PN_ID = pll_old.PN_ID
    INNER JOIN QLPN.PN_LAI_LICHS plls
        ON pll_old.SO_HSLD = plls.LL_SO_HO_SO_LAN_DAU
    LEFT JOIN QLPN.DM_CO_QUANS cq_dn
        ON cq_dn.CQ_MA = ct.MA_CQ_DN_CHUYEN
       AND NVL(cq_dn.IS_DELETED, 0) = 0
    LEFT JOIN QLPN.DM_TRUONG_HOP_CHUYEN_TRAIS thct
        ON thct.THCT_MA = ct.MA_TRUONG_HOP_CHUYEN
       AND NVL(thct.IS_DELETED, 0) = 0
    LEFT JOIN QLPN.DM_TRAI_GIAMS tg_den
        ON tg_den.TG_MA = ct.MA_CQ_TRAI_DEN
       AND NVL(tg_den.IS_DELETED, 0) = 0
    LEFT JOIN QLPN.MAPPING_PROVINCE mp_dp_dn
        ON TRIM(TO_CHAR(mp_dp_dn.MA_TINH_OLD)) = TRIM(TO_CHAR(ct.MA_DP_DN_CHUYEN))
    LEFT JOIN QLPN.DM_TINH_THANH_PHO dttp_dn
        ON TRIM(mp_dp_dn.MA_TINH_NEW) = TRIM(dttp_dn.TTP_MA)
       AND NVL(dttp_dn.IS_DELETED, 0) = 0
    LEFT JOIN QLPN.MAPPING_PROVINCE mp_dp_trai
        ON TRIM(TO_CHAR(mp_dp_trai.MA_TINH_OLD)) = TRIM(TO_CHAR(ct.MA_DP_TRAI_DEN))
    LEFT JOIN QLPN.DM_TINH_THANH_PHO dttp_trai
        ON TRIM(mp_dp_trai.MA_TINH_NEW) = TRIM(dttp_trai.TTP_MA)
       AND NVL(dttp_trai.IS_DELETED, 0) = 0
)
SELECT
    s.PNCT_CONG_VAN_DE_NGHI_SO,
    s.PNCT_CONG_VAN_DE_NGHI_NGAY,
    s.PNCT_CO_QUAN_DE_NGHI_CHUYEN_ID,
    s.PNCT_SO_QDDIEU_CHUYEN,
    s.PNCT_NGAY_QDCHUYEN,
    s.PNCT_TRUONG_HOP_CHUYEN_ID,
    s.PNCT_NGAY_CHUYEN,
    s.PNCT_TRAI_DEN_ID,
    s.PNCT_NGAY_TRO_LAI,
    s.PNCT_SO_QDDIEU_CHUYEN_LAI,
    s.PNCT_NGAY_QDDIEU_CHUYEN_LAI,
    s.PNCT_GHI_CHU,
    s.PNCT_LAI_LICH_ID,
    s.PNCT_CO_QUAN_DE_NGHI_DIA_PHUONG_ID,
    s.PNCT_TRAI_DEN_DIA_PHUONG_ID,
    s.CREATION_TIME,
    s.IS_DELETED
FROM chuyen_trai_src s;
COMMIT;