DROP TABLE QLPN.MAPPING_PROVINCE CASCADE CONSTRAINTS PURGE;

-- Tạo cấu trúc bảng (không nạp dòng)
CREATE TABLE QLPN.MAPPING_PROVINCE AS
SELECT
  mdco.MA AS MA_TINH_OLD,
  mdco.ND AS TEN_TINH_OLD,
  dttp.TTP_MA AS MA_TINH_NEW,
  dttp.TTP_TEN AS TEN_TINH_NEW
FROM
  QLPN_OLD.MA_DP mdco
  LEFT JOIN QLPN.DM_TINH_THANH_PHO dttp ON FN_NORMALIZE_VN (mdco.ND) = FN_NORMALIZE_VN (dttp.TTP_TEN)
WHERE
  mdco.MA_HIEN_TRANG = 1
  AND 1 = 0;

-- Nạp dữ liệu
INSERT INTO
  QLPN.MAPPING_PROVINCE (
    MA_TINH_OLD,
    TEN_TINH_OLD,
    MA_TINH_NEW,
    TEN_TINH_NEW
  )
SELECT
  mdco.MA AS MA_TINH_OLD,
  mdco.ND AS TEN_TINH_OLD,
  dttp.TTP_MA AS MA_TINH_NEW,
  dttp.TTP_TEN AS TEN_TINH_NEW
FROM
  QLPN_OLD.MA_DP mdco
  LEFT JOIN QLPN.DM_TINH_THANH_PHO dttp ON FN_NORMALIZE_VN (mdco.ND) = FN_NORMALIZE_VN (dttp.TTP_TEN)
WHERE
  mdco.MA_HIEN_TRANG = 1;

COMMIT;

COMMENT ON TABLE QLPN.MAPPING_PROVINCE IS 'Mapping tỉnh: MA_DP (QLPN_OLD) -> DM_TINH_THANH_PHO (FN_NORMALIZE_VN).';