DELETE FROM "QLPN"."PHAM_NHAN_PHAN_DOI";
INSERT INTO "QLPN"."PHAM_NHAN_PHAN_DOI" (
    PNPD_NGAY_CHUYEN,
    PNPD_PHAN_TRAI_ID,
    PNPD_PHAN_DOI_ID,
    PNPD_GHI_CHU,
    PNPD_LAI_LICH_ID,
    CREATION_TIME,
    CREATOR_USER_ID,
    LAST_MODIFICATION_TIME,
    LAST_MODIFIER_USER_ID,
    IS_DELETED,
    DELETER_USER_ID,
    DELETION_TIME
)
SELECT
    A.NGAY_CHUYEN_DEN                         AS PNPD_NGAY_CHUYEN,
    D.PD_DM_PHAN_TRAI_ID                      AS PNPD_PHAN_TRAI_ID,
    D.ID                                      AS PNPD_PHAN_DOI_ID,
    A.GHI_CHU                                 AS PNPD_GHI_CHU,
    C.ID                                      AS PNPD_LAI_LICH_ID,
    SYSDATE                                   AS CREATION_TIME,
    CAST(NULL AS NUMBER(19))                  AS CREATOR_USER_ID,
    CAST(NULL AS TIMESTAMP(7))                AS LAST_MODIFICATION_TIME,
    CAST(NULL AS NUMBER(19))                  AS LAST_MODIFIER_USER_ID,
    0                                         AS IS_DELETED,
    CAST(NULL AS NUMBER(19))                  AS DELETER_USER_ID,
    CAST(NULL AS TIMESTAMP(7))                AS DELETION_TIME
FROM "QLPN_OLD"."PN_PHAN_DOI" A
INNER JOIN "QLPN_OLD"."PN_LAI_LICH" B ON A.PN_ID = B.PN_ID
INNER JOIN "QLPN"."PN_LAI_LICHS" C ON B.SO_HSLD = C.LL_SO_HO_SO_LAN_DAU
LEFT JOIN "QLPN"."DM_PHAN_DOIS" D ON A.MA_PHAN_DOI_DEN = D.PD_MA;