-- =============================================================================
-- SCRIPT_THA_CDK.sql — Nạp phân hệ tha có điều kiện (QLPN)
-- DATE: MAR 17, 2026
-- =============================================================================
-- Hiện tại: THA_CO_DIEU_KIENS từ QLPN_OLD.PN_THA_CO_DK.
-- Quy ước migrate: .cursor/rules/sql-migration-qlpn-conventions.mdc
--   - Không INSERT: ID, CREATOR_USER_ID, LAST_MODIFICATION_TIME,
--     LAST_MODIFIER_USER_ID, DELETER_USER_ID, DELETION_TIME
--   - MA_DP* → MAPPING_PROVINCE + DM_TINH_THANH_PHO (ID tỉnh), không DM_DON_VI_HANH_CHINH
-- =============================================================================
TRUNCATE TABLE QLPN.THA_CO_DIEU_KIENS;
INSERT /*+ APPEND */ INTO QLPN.THA_CO_DIEU_KIENS (
    NGAY_XET,
    TINH_TRANG_ID,
    SO_QUYET_DINH_THA,
    NGAY_QUYET_DINH_THA,
    TOA_QUYET_DINH_THA_ID,
    DIA_PHUONG_QUYET_DINH_THA_ID,
    NGAY_THA,
    NGAY_TRINH_DIEN,
    LY_DO_TRO_LAI_ID,
    LY_DO_CHI_TIET,
    SO_QUYET_DINH_LAI,
    NGAY_QUYET_DINH,
    TOA_QUYET_DINH_LAI_ID,
    DIA_PHUONG_QUYET_DINH_LAI_ID,
    NGAY_QUYET_DINH_TRO_LAI,
    NGAY_BAT_LAI,
    PHAM_NHAN_ID,
    CREATION_TIME,
    IS_DELETED,
    QQCT_PHIEU,
    NHAN_XET,
    DANH_GIA_CAI_TAO_ID
)
WITH tha_cdk_src AS (
    SELECT
        CAST(tt.NGAY_XET_TT AS TIMESTAMP(7)) AS NGAY_XET,
        dtcdk.ID AS TINH_TRANG_ID,
        tt.SO_QD_TT AS SO_QUYET_DINH_THA,
        CAST(tt.NGAY_QD_TT AS TIMESTAMP(7)) AS NGAY_QUYET_DINH_THA,
        dcq_tt.ID AS TOA_QUYET_DINH_THA_ID,
        dttp_tt.ID AS DIA_PHUONG_QUYET_DINH_THA_ID,
        CAST(tt.NGAY_THA_TT AS TIMESTAMP(7)) AS NGAY_THA,
        CAST(tt.NGAY_TRINH_DIEN_TT AS TIMESTAMP(7)) AS NGAY_TRINH_DIEN,
        ldtl.ID AS LY_DO_TRO_LAI_ID,
        tt.LY_DO_TROLAI_CHITIET AS LY_DO_CHI_TIET,
        tt.SO_QD_TL AS SO_QUYET_DINH_LAI,
        CAST(tt.NGAY_QD_TL AS TIMESTAMP(7)) AS NGAY_QUYET_DINH,
        dcq_tl.ID AS TOA_QUYET_DINH_LAI_ID,
        dttp_tl.ID AS DIA_PHUONG_QUYET_DINH_LAI_ID,
        CAST(tt.NGAY_QD_TRO_LAI AS TIMESTAMP(7)) AS NGAY_QUYET_DINH_TRO_LAI,
        CAST(tt.NGAY_TRO_LAI_TRAI AS TIMESTAMP(7)) AS NGAY_BAT_LAI,
        pll2.ID AS PHAM_NHAN_ID,
        SYSTIMESTAMP AS CREATION_TIME,
        0 AS IS_DELETED,
        tt.KQCT_PHIEU_TT AS QQCT_PHIEU,
        tt.NHAN_XET_TT || CHR(10) || tt.DANH_GIA_CAI_TAO_TT AS NHAN_XET,
        dxlct.ID AS DANH_GIA_CAI_TAO_ID
    FROM QLPN_OLD.PN_THA_CO_DK tt
    LEFT JOIN QLPN_OLD.PN_LAI_LICH pll_old
        ON pll_old.PN_ID = tt.PN_ID
    INNER JOIN QLPN.PN_LAI_LICHS pll2
        ON pll2.LL_SO_HO_SO_LAN_DAU = pll_old.SO_HSLD
    LEFT JOIN QLPN.DM_THA_CO_DIEU_KIENS dtcdk
        ON dtcdk.TCDK_MA = tt.MA_DUOC_TT
    LEFT JOIN QLPN.DM_CO_QUANS dcq_tt
        ON dcq_tt.CQ_MA = tt.MA_CQ_TOA_QD_TT
    LEFT JOIN QLPN.MAPPING_PROVINCE mp_dp_tt
        ON TRIM(TO_CHAR(mp_dp_tt.MA_TINH_OLD)) = TRIM(TO_CHAR(tt.MA_DP_TOA_QD_TT))
    LEFT JOIN QLPN.DM_TINH_THANH_PHO dttp_tt
        ON TRIM(mp_dp_tt.MA_TINH_NEW) = TRIM(dttp_tt.TTP_MA)
       AND NVL(dttp_tt.IS_DELETED, 0) = 0
    LEFT JOIN QLPN.DM_LY_DO_TRO_LAIES ldtl
        ON ldtl.LDTL_MA = tt.MA_LY_DO_TRO_LAI
    LEFT JOIN QLPN.DM_CO_QUANS dcq_tl
        ON dcq_tl.CQ_MA = tt.MA_CQ_TOA_QD_TL
    LEFT JOIN QLPN.MAPPING_PROVINCE mp_dp_tl
        ON TRIM(TO_CHAR(mp_dp_tl.MA_TINH_OLD)) = TRIM(TO_CHAR(tt.MA_DP_TOA_QD_TL))
    LEFT JOIN QLPN.DM_TINH_THANH_PHO dttp_tl
        ON TRIM(mp_dp_tl.MA_TINH_NEW) = TRIM(dttp_tl.TTP_MA)
       AND NVL(dttp_tl.IS_DELETED, 0) = 0
    LEFT JOIN QLPN.DM_XEP_LOAI_CAI_TAOS dxlct
        ON dxlct.XLCT_TEN = tt.DANH_GIA_CAI_TAO_TT
)
SELECT
    s.NGAY_XET,
    s.TINH_TRANG_ID,
    s.SO_QUYET_DINH_THA,
    s.NGAY_QUYET_DINH_THA,
    s.TOA_QUYET_DINH_THA_ID,
    s.DIA_PHUONG_QUYET_DINH_THA_ID,
    s.NGAY_THA,
    s.NGAY_TRINH_DIEN,
    s.LY_DO_TRO_LAI_ID,
    s.LY_DO_CHI_TIET,
    s.SO_QUYET_DINH_LAI,
    s.NGAY_QUYET_DINH,
    s.TOA_QUYET_DINH_LAI_ID,
    s.DIA_PHUONG_QUYET_DINH_LAI_ID,
    s.NGAY_QUYET_DINH_TRO_LAI,
    s.NGAY_BAT_LAI,
    s.PHAM_NHAN_ID,
    s.CREATION_TIME,
    s.IS_DELETED,
    s.QQCT_PHIEU,
    s.NHAN_XET,
    s.DANH_GIA_CAI_TAO_ID
FROM tha_cdk_src s;
COMMIT;