DELETE FROM QLPN.PN_DU_DIEU_KIEN_XET_THAS;
DELETE FROM QLPN.PN_DOT_THA_CO_DIEU_KIENS;

INSERT INTO QLPN.PN_DOT_THA_CO_DIEU_KIENS
(
DTCDK_NGAY_XET,
DTCDK_NGAY_HOP,
DTCDK_SO_PHIEU,
DTCDK_SO_GCN_TU,
DTCDK_DM_CO_QUAN_ID,
CREATION_TIME,
IS_DELETED
)
SELECT
NGAY_XET_THA,
NGAY_HOP_XET,
TU_SO_PHIEU,
TU_SO_GCN,
CQ.ID MA_CQ_TOA_QD_THA,
CAST(SYSTIMESTAMP AS TIMESTAMP(7)) AS CREATION_TIME,
0 AS IS_DELETED
FROM QLPN_OLD.PN_OPEN_KY_THA_CO_DK TCDK
LEFT JOIN QLPN.DM_CO_QUANS CQ  ON CQ.CQ_MA = TCDK.MA_CQ_TOA_QD_THA;

INSERT INTO QLPN.PN_DU_DIEU_KIEN_XET_THAS (
    PN_DOT_THA_CO_DIEU_KIEN_ID,
    PN_LAI_LICH_ID,

    CREATION_TIME,
    CREATOR_USER_ID,
    LAST_MODIFICATION_TIME,
    LAST_MODIFIER_USER_ID,
    IS_DELETED,
    DELETER_USER_ID,
    DELETION_TIME
)
SELECT
    dot.ID,
    pll2.ID,

    /* audit */
    SYSTIMESTAMP,        -- CREATION_TIME
    NULL,                -- CREATOR_USER_ID
    SYSTIMESTAMP,                -- LAST_MODIFICATION_TIME
    NULL,                -- LAST_MODIFIER_USER_ID
    0,                   -- IS_DELETED
    NULL,                -- DELETER_USER_ID
    NULL                 -- DELETION_TIME

FROM QLPN_OLD.PN_THA_CO_DK t

/* map đợt xét */
JOIN QLPN.PN_DOT_THA_CO_DIEU_KIENS dot
    ON dot.DTCDK_NGAY_XET = t.NGAY_XET_TT

/* map PN */
LEFT JOIN QLPN_OLD.PN_LAI_LICH pll
    ON pll.PN_ID = t.PN_ID

INNER JOIN QLPN.PN_LAI_LICHS pll2
    ON pll2.LL_SO_HO_SO_LAN_DAU = pll.SO_HSLD;