DELETE FROM QLPN.PN_HINH_PHAT_BO_SUNGS;
INSERT INTO QLPN.PN_HINH_PHAT_BO_SUNGS
(
    HPBS_HINH_PHAT,
    HPBS_MA_PHAM_NHAN,
    HPBS_THOI_HAN,
    HPBS_TONG_TIEN_PHAT,
    HPBS_HE_SO,
    HPBS_GHI_CHU,
    HPBS_GHI_CHU_CHI_TIET,
    CREATION_TIME,
    IS_DELETED,
    HPBS_TONG_TIEN_CON_LAI
)
SELECT  /*+ USE_HASH( LL  LLN) */
    DMHPBS.ID MA_HINH_PHAT,
    LLN.ID,
    DMMTG.ID MA_MUC_THOI_HAN,
    TONG_TIEN_PHAT,
    HST.ID MA_HE_SO_TIEN,
    DMGCHPBS.ID MA_GHI_CHU_HPBS,
    GHI_CHU_HPBS_HP,
    CAST(SYSTIMESTAMP AS TIMESTAMP(7)) AS CREATION_TIME,
    0 AS IS_DELETED,
    TONG_TIEN_PHAT-NVL(TONG_DA_NOP,0) as HPBS_TONG_TIEN_CON_LAI
FROM QLPN_OLD.PN_HPBS_HINH_PHAT HPBS
INNER JOIN QLPN_OLD.PN_LAI_LICH LL ON HPBS.PN_ID = LL.PN_ID
INNER JOIN QLPN.PN_LAI_LICHS LLN ON LL.SO_HSLD = LLN.LL_SO_HO_SO_LAN_DAU
left JOIN QLPN.DM_HE_SO_TIENS HST ON HST.HST_MA = HPBS.MA_HE_SO_TIEN
left JOIN QLPN.DM_HINH_PHAT_BO_SUNGS DMHPBS ON DMHPBS.HPBS_MA = HPBS.MA_HINH_PHAT
left JOIN QLPN.DM_GHI_CHU_HINH_PHAT_BO_SUNGS DMGCHPBS ON DMGCHPBS.GCHPBS_MA = HPBS.MA_GHI_CHU_HPBS
left JOIN QLPN.DM_MA_THOI_GIANS DMMTG ON DMMTG.MTG_MA = HPBS.MA_MUC_THOI_HAN