DELETE FROM QLPN.MO_KY_XEP_LOAI_CAI_TAO_PN_LAI_LICH;
DELETE FROM QLPN.MO_KY_XEP_LOAI_CAI_TAOS;
INSERT INTO QLPN.MO_KY_XEP_LOAI_CAI_TAOS (
    NAM_XEP_LOAI,
    TU_NGAY,
    DEN_NGAY,
    NGAY_DEN_TRAI_TU,
    TRANG_THAI,
    CREATION_TIME,
    CREATOR_USER_ID,
    LAST_MODIFICATION_TIME,
    LAST_MODIFIER_USER_ID,
    IS_DELETED,
    DELETER_USER_ID,
    DELETION_TIME,
    KY_XEP_LOAI,
    NGAY_HOP_XEP_LOAI,
    NGAY_QDXEP_LOAI,
    NGAY_TBCHO_GIA_DINH,
    SO_QUYET_DINH_TU,
    SO_THONG_BAO_TU
)
SELECT
    okxl.NAM_XL,
    CAST(okxl.TU_NGAY_XL AS TIMESTAMP),
    CAST(okxl.DEN_NGAY_XL AS TIMESTAMP),
    CAST(okxl.TU_NGAY_DEN_TRAI AS TIMESTAMP),
    /* TRANG_THAI: CLOSE = 0, OPEN = 1 */
    CASE
        WHEN UPPER(okxl.ACTION) = 'CLOSE' THEN 0
        ELSE 1
    END,
    /* Audit */
    SYSTIMESTAMP,
    NULL,
    SYSTIMESTAMP,
    NULL,
    0,
    NULL,
    NULL,
    okxl.KY_XEP_LOAI,
    CAST(okxl.NGAY_HOP_XEP_LOAI AS TIMESTAMP),
    CAST(okxl.NGAY_QD_XL AS TIMESTAMP),
    CAST(okxl.NGAY_TB_XL AS TIMESTAMP),
    TO_CHAR(okxl.TU_SO_QD),
    TO_CHAR(okxl.TU_SO_TB)
FROM (
    SELECT okxl.*,
           ROW_NUMBER() OVER (
               ORDER BY GREATEST(
                   NVL(okxl.NGAY_HOP_XEP_LOAI, DATE '1900-01-01'),
                   NVL(okxl.NGAY_QD_XL, DATE '1900-01-01'),
                   NVL(okxl.NGAY_TB_XL, DATE '1900-01-01')
               ) DESC,
               okxl.NAM_XL DESC  -- tie-break thêm cho ổn định
           ) rn
    FROM QLPN_OLD.PN_OPEN_KY_XEP_LOAI okxl
) okxl;
INSERT INTO QLPN.MO_KY_XEP_LOAI_CAI_TAO_PN_LAI_LICH (
    MO_KY_XEP_LOAI_CAI_TAOS_ID,
    PN_LAI_LICHS_ID
)
SELECT
    (
        SELECT t.ID
        FROM QLPN.MO_KY_XEP_LOAI_CAI_TAOS t
        ORDER BY t.CREATION_TIME DESC, t.NAM_XEP_LOAI DESC
        FETCH FIRST 1 ROW ONLY
    ) AS MO_KY_ID,
    pll2.ID
FROM QLPN_OLD.PN_KY_XEP_LOAI pkxl
LEFT JOIN QLPN_OLD.PN_LAI_LICH pll
    ON pll.PN_ID = pkxl.PN_ID
INNER JOIN QLPN.PN_LAI_LICHS pll2
    ON pll2.LL_SO_HO_SO_LAN_DAU = pll.SO_HSLD;
--DROP TABLE QLPN.MAP_KY_XL;